---
name: Text-FindLinks
version: 0.01
author:
  - 'Tomáš Znamenáček <zoul@fleuron.cz>'
abstract: The great new Text::FindLinks!
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.35
provides:
  Text::FindLinks:
    file: lib/Text/FindLinks.pm
    version: 0.01
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
